// script.js

// Dictionary of cities and counties
const cityCountyMapping = {
    "Lynwood": "Los Angeles",
    "Carmel-by-the-Sea": "Monterey",
    "West Covina": "Los Angeles",
    "Winters": "Yolo",
    "Newport Beach": "Orange",
    "Guadalupe": "Santa Barbara",
    "Plymouth": "Amador",
    "Duarte": "Los Angeles",
    "Yountville": "Napa",
    "Oceanside": "San Diego",
    "Chowchilla": "Madera",
    "Escalon": "San Joaquin",
    "Costa Mesa": "Orange",
    "Desert Hot Springs": "Riverside",
    "Fort Bragg": "Mendocino",
    "Oroville": "Butte",
    "Exeter": "Tulare",
    "Rio Vista": "Solano",
    "Mount Shasta": "Siskiyou",
    "Porterville": "Tulare",
    "Hillsborough": "San Mateo",
    "Loma Linda": "San Bernardino",
    "Chula Vista": "San Diego",
    "Shasta Lake": "Shasta",
    "Oxnard": "Ventura",
    "Fortuna": "Humboldt",
    "Turlock": "Stanislaus",
    "Lathrop": "San Joaquin",
    "Placerville": "El Dorado",
    "La Cañada Flintridge": "Los Angeles",
    "Brentwood": "Contra Costa",
    "Paradise": "Butte",
    "Norwalk": "Los Angeles",
    "Laguna Woods": "Orange",
    "Calexico": "Imperial",
    "Chico": "Butte",
    "Fillmore": "Ventura",
    "Dinuba": "Tulare",
    "Watsonville": "Santa Cruz",
    "South El Monte": "Los Angeles",
    "Ripon": "San Joaquin",
    "Moorpark": "Ventura",
    "Port Hueneme": "Ventura",
    "Suisun City": "Solano",
    "Beverly Hills": "Los Angeles",
    "Laguna Beach": "Orange",
    "Poway": "San Diego",
    "Mission Viejo": "Orange",
    "Merced": "Merced",
    "Reedley": "Fresno",
    "Hughson": "Stanislaus",
    "Atwater": "Merced",
    "Santa Fe Springs": "Los Angeles",
    "Redondo Beach": "Los Angeles",
    "Atascadero": "San Luis Obispo",
    "Gardena": "Los Angeles",
    "Moreno Valley": "Riverside",
    "Loomis": "Placer",
    "San Dimas": "Los Angeles",
    "Temple City": "Los Angeles",
    "Thousand Oaks": "Ventura",
    "Stanton": "Orange",
    "Pacifica": "San Mateo",
    "Solana Beach": "San Diego",
    "California City": "Kern",
    "Amador City": "Amador",
    "Torrance": "Los Angeles",
    "Palmdale": "Los Angeles",
    "San Leandro": "Alameda",
    "Hawaiian Gardens": "Los Angeles",
    "Colfax": "Placer",
    "Salinas": "Monterey",
    "Orange": "Orange",
    "La Verne": "Los Angeles",
    "Patterson": "Stanislaus",
    "Lompoc": "Santa Barbara",
    "Long Beach": "Los Angeles",
    "San Pablo": "Contra Costa",
    "Fullerton": "Orange",
    "Signal Hill": "Los Angeles",
    "Nevada City": "Nevada",
    "Solvang": "Santa Barbara",
    "Pinole": "Contra Costa",
    "Ojai": "Ventura",
    "Biggs": "Butte",
    "Belmont": "San Mateo",
    "Chino": "San Bernardino",
    "Bishop": "Inyo",
    "Seal Beach": "Orange",
    "McFarland": "Kern",
    "Canyon Lake": "Riverside",
    "East Palo Alto": "San Mateo",
    "Lodi": "San Joaquin",
    "Roseville": "Placer",
    "Grand Terrace": "San Bernardino",
    "Huntington Beach": "Orange",
    "Blue Lake": "Humboldt",
    "Rancho Cucamonga": "San Bernardino",
    "Stockton": "San Joaquin",
    "Rancho Mirage": "Riverside",
    "El Segundo": "Los Angeles",
    "Yorba Linda": "Orange",
    "Wildomar": "Riverside",
    "Davis": "Yolo",
    "Tustin": "Orange",
    "Colton": "San Bernardino",
    "Needles": "San Bernardino",
    "Etna": "Siskiyou",
    "Lemon Grove": "San Diego",
    "Manhattan Beach": "Los Angeles",
    "Chino Hills": "San Bernardino",
    "Daly City": "San Mateo",
    "Los Angeles": "Los Angeles",
    "Adelanto": "San Bernardino",
    "San Francisco": "San Francisco",
    "Orland": "Glenn",
    "Atherton": "San Mateo",
    "Hermosa Beach": "Los Angeles",
    "Manteca": "San Joaquin",
    "Carpinteria": "Santa Barbara",
    "Millbrae": "San Mateo",
    "San Bruno": "San Mateo",
    "Carson": "Los Angeles",
    "Compton": "Los Angeles",
    "Fremont": "Alameda",
    "Dublin": "Alameda",
    "Bell": "Los Angeles",
    "Indio": "Riverside",
    "Hercules": "Contra Costa",
    "Bakersfield": "Kern",
    "Ventura": "Ventura",
    "Upland": "San Bernardino",
    "San Carlos": "San Mateo",
    "Monterey Park": "Los Angeles",
    "Alturas": "Modoc",
    "Woodside": "San Mateo",
    "Angels Camp": "Calaveras",
    "San Gabriel": "Los Angeles",
    "South Gate": "Los Angeles",
    "South Lake Tahoe": "El Dorado",
    "San Juan Bautista": "San Benito",
    "Coachella": "Riverside",
    "San Ramon": "Contra Costa",
    "Gilroy": "Santa Clara",
    "Orange Cove": "Fresno",
    "Morgan Hill": "Santa Clara",
    "Maywood": "Los Angeles",
    "Del Mar": "San Diego",
    "Pittsburg": "Contra Costa",
    "Dunsmuir": "Siskiyou",
    "San Clemente": "Orange",
    "Cupertino": "Santa Clara",
    "Brisbane": "San Mateo",
    "Big Bear Lake": "San Bernardino",
    "Cypress": "Orange",
    "Monterey": "Monterey",
    "Sonora": "Tuolumne",
    "South San Francisco": "San Mateo",
    "El Monte": "Los Angeles",
    "Gridley": "Butte",
    "Irwindale": "Los Angeles",
    "King City": "Monterey",
    "Williams": "Colusa",
    "Highland": "San Bernardino",
    "Tulelake": "Siskiyou",
    "Willits": "Mendocino",
    "San Diego": "San Diego",
    "Antioch": "Contra Costa",
    "Kerman": "Fresno",
    "Calabasas": "Los Angeles",
    "Farmersville": "Tulare",
    "City of Industry": "Los Angeles",
    "El Centro": "Imperial",
    "Rancho Palos Verdes": "Los Angeles",
    "Arroyo Grande": "San Luis Obispo",
    "Yuba City": "Sutter",
    "Avalon": "Los Angeles",
    "Novato": "Marin",
    "Tracy": "San Joaquin",
    "National City": "San Diego",
    "Woodlake": "Tulare",
    "Buena Park": "Orange",
    "Murrieta": "Riverside",
    "Fowler": "Fresno",
    "Malibu": "Los Angeles",
    "Fountain Valley": "Orange",
    "Diamond Bar": "Los Angeles",
    "Westminster": "Orange",
    "Ridgecrest": "Kern",
    "Tiburon": "Marin",
    "Walnut": "Los Angeles",
    "Los Banos": "Merced",
    "Tehama": "Tehama",
    "Lindsay": "Tulare",
    "Buellton": "Santa Barbara",
    "Dorris": "Siskiyou",
    "Bradbury": "Los Angeles",
    "Saratoga": "Santa Clara",
    "Richmond": "Contra Costa",
    "Redding": "Shasta",
    "Sunnyvale": "Santa Clara",
    "Calipatria": "Imperial",
    "Colma": "San Mateo",
    "Oakley": "Contra Costa",
    "La Palma": "Orange",
    "Berkeley": "Alameda",
    "Clearlake": "Lake",
    "Imperial Beach": "San Diego",
    "Larkspur": "Marin",
    "Colusa": "Colusa",
    "San Jose": "Santa Clara",
    "Point Arena": "Mendocino",
    "San Jacinto": "Riverside",
    "La Puente": "Los Angeles",
    "Newman": "Stanislaus",
    "Rolling Hills Estates": "Los Angeles",
    "Ukiah": "Mendocino",
    "Modesto": "Stanislaus",
    "Villa Park": "Orange",
    "Simi Valley": "Ventura",
    "Redlands": "San Bernardino",
    "Sacramento": "Sacramento",
    "Aliso Viejo": "Orange",
    "Half Moon Bay": "San Mateo",
    "San Marino": "Los Angeles",
    "Healdsburg": "Sonoma",
    "Corona": "Riverside",
    "Hollister": "San Benito",
    "Ferndale": "Humboldt",
    "Yreka": "Siskiyou",
    "Pismo Beach": "San Luis Obispo",
    "Clayton": "Contra Costa",
    "Lemoore": "Kings",
    "San Juan Capistrano": "Orange",
    "Palos Verdes Estates": "Los Angeles",
    "San Rafael": "Marin",
    "Perris": "Riverside",
    "Lafayette": "Contra Costa",
    "Calistoga": "Napa",
    "Rialto": "San Bernardino",
    "Trinidad": "Humboldt",
    "Union City": "Alameda",
    "La Habra Heights": "Los Angeles",
    "Inglewood": "Los Angeles",
    "Wasco": "Kern",
    "Encinitas": "San Diego",
    "Del Rey Oaks": "Monterey",
    "Rohnert Park": "Sonoma",
    "Twentynine Palms": "San Bernardino",
    "South Pasadena": "Los Angeles",
    "Citrus Heights": "Sacramento",
    "Los Altos": "Santa Clara",
    "Sierra Madre": "Los Angeles",
    "Jackson": "Amador",
    "Morro Bay": "San Luis Obispo",
    "Santa Maria": "Santa Barbara",
    "Baldwin Park": "Los Angeles",
    "Loyalton": "Sierra",
    "Lancaster": "Los Angeles",
    "Truckee": "Nevada",
    "Garden Grove": "Orange",
    "Napa": "Napa",
    "San Anselmo": "Marin",
    "Temecula": "Riverside",
    "Sand City": "Monterey",
    "Grass Valley": "Nevada",
    "Lawndale": "Los Angeles",
    "Belvedere": "Marin",
    "Isleton": "Sacramento",
    "Moraga": "Contra Costa",
    "La Habra": "Orange",
    "Concord": "Contra Costa",
    "Hidden Hills": "Los Angeles",
    "Lake Elsinore": "Riverside",
    "La Mirada": "Los Angeles",
    "Arcata": "Humboldt",
    "Soledad": "Monterey",
    "Grover Beach": "San Luis Obispo",
    "Lincoln": "Placer",
    "Jurupa Valley": "Riverside",
    "Apple Valley": "San Bernardino",
    "Waterford": "Stanislaus",
    "Lomita": "Los Angeles",
    "Ione": "Amador",
    "Santa Clarita": "Los Angeles",
    "West Sacramento": "Yolo",
    "Dana Point": "Orange",
    "Live Oak": "Sutter",
    "Hayward": "Alameda",
    "Lakewood": "Los Angeles",
    "Palm Desert": "Riverside",
    "Coalinga": "Fresno",
    "Palm Springs": "Riverside",
    "Cloverdale": "Sonoma",
    "Shafter": "Kern",
    "Alameda": "Alameda",
    "Rio Dell": "Humboldt",
    "Campbell": "Santa Clara",
    "Mill Valley": "Marin",
    "Martinez": "Contra Costa",
    "Seaside": "Monterey",
    "Newark": "Alameda",
    "Rancho Santa Margarita": "Orange",
    "Redwood City": "San Mateo",
    "Folsom": "Sacramento",
    "Pico Rivera": "Los Angeles",
    "Delano": "Kern",
    "Vacaville": "Solano",
    "Willows": "Glenn",
    "San Mateo": "San Mateo",
    "Emeryville": "Alameda",
    "Lakeport": "Lake",
    "Bell Gardens": "Los Angeles",
    "Los Altos Hills": "Santa Clara",
    "Santa Paula": "Ventura",
    "Visalia": "Tulare",
    "Scotts Valley": "Santa Cruz",
    "Holtville": "Imperial",
    "Camarillo": "Ventura",
    "Beaumont": "Riverside",
    "San Luis Obispo": "San Luis Obispo",
    "Susanville": "Lassen",
    "Corte Madera": "Marin",
    "Blythe": "Riverside",
    "Montebello": "Los Angeles",
    "Galt": "Sacramento",
    "Rancho Cordova": "Sacramento",
    "Paso Robles": "San Luis Obispo",
    "Marina": "Monterey",
    "Rolling Hills": "Los Angeles",
    "Capitola": "Santa Cruz",
    "Ross": "Marin",
    "Banning": "Riverside",
    "Indian Wells": "Riverside",
    "La Quinta": "Riverside",
    "Norco": "Riverside",
    "Irvine": "Orange",
    "Burbank": "Los Angeles",
    "Woodland": "Yolo",
    "Santa Clara": "Santa Clara",
    "Milpitas": "Santa Clara",
    "Yucca Valley": "San Bernardino",
    "Los Alamitos": "Orange",
    "Commerce": "Los Angeles",
    "San Bernardino": "San Bernardino",
    "Culver City": "Los Angeles",
    "Sebastopol": "Sonoma",
    "Laguna Niguel": "Orange",
    "Kingsburg": "Fresno",
    "Victorville": "San Bernardino",
    "Maricopa": "Kern",
    "Orinda": "Contra Costa",
    "Fresno": "Fresno",
    "Escondido": "San Diego",
    "Sausalito": "Marin",
    "Hawthorne": "Los Angeles",
    "Fairfield": "Solano",
    "Riverside": "Riverside",
    "West Hollywood": "Los Angeles",
    "Vista": "San Diego",
    "St. Helena": "Napa",
    "Covina": "Los Angeles",
    "Paramount": "Los Angeles",
    "Downey": "Los Angeles",
    "El Cajon": "San Diego",
    "Agoura Hills": "Los Angeles",
    "American Canyon": "Napa",
    "Barstow": "San Bernardino",
    "El Cerrito": "Contra Costa",
    "Windsor": "Sonoma",
    "Gonzales": "Monterey",
    "Yucaipa": "San Bernardino",
    "Walnut Creek": "Contra Costa",
    "Cathedral City": "Riverside",
    "Cotati": "Sonoma",
    "Monrovia": "Los Angeles",
    "Huron": "Fresno",
    "Piedmont": "Alameda",
    "Foster City": "San Mateo",
    "Arcadia": "Los Angeles",
    "Hanford": "Kings",
    "Corcoran": "Kings",
    "Placentia": "Orange",
    "Marysville": "Yuba",
    "Portola Valley": "San Mateo",
    "Pomona": "Los Angeles",
    "Parlier": "Fresno",
    "Weed": "Siskiyou",
    "Tulare": "Tulare",
    "Sutter Creek": "Amador",
    "Santa Ana": "Orange",
    "Tehachapi": "Kern",
    "Bellflower": "Los Angeles",
    "Huntington Park": "Los Angeles",
    "Carlsbad": "San Diego",
    "Coronado": "San Diego",
    "Elk Grove": "Sacramento",
    "Riverbank": "Stanislaus",
    "Portola": "Plumas",
    "Danville": "Contra Costa",
    "Brea": "Orange",
    "Brawley": "Imperial",
    "Artesia": "Los Angeles",
    "Gustine": "Merced",
    "Anderson": "Shasta",
    "Rocklin": "Placer",
    "Dos Palos": "Merced",
    "Palo Alto": "Santa Clara",
    "Montclair": "San Bernardino",
    "Cudahy": "Los Angeles",
    "Santee": "San Diego",
    "Ceres": "Stanislaus",
    "Greenfield": "Monterey",
    "Pasadena": "Los Angeles",
    "Santa Barbara": "Santa Barbara",
    "Burlingame": "San Mateo",
    "Sonoma": "Sonoma",
    "Whittier": "Los Angeles",
    "San Fernando": "Los Angeles",
    "Selma": "Fresno",
    "Glendora": "Los Angeles",
    "Goleta": "Santa Barbara",
    "Santa Cruz": "Santa Cruz",
    "Monte Sereno": "Santa Clara",
    "Benicia": "Solano",
    "Menlo Park": "San Mateo",
    "Auburn": "Placer",
    "Claremont": "Los Angeles",
    "Firebaugh": "Fresno",
    "Wheatland": "Yuba",
    "Fort Jones": "Siskiyou",
    "Mountain View": "Santa Clara",
    "Cerritos": "Los Angeles",
    "Arvin": "Kern",
    "Vernon": "Los Angeles",
    "Corning": "Tehama",
    "Oakland": "Alameda",
    "Taft": "Kern",
    "Calimesa": "Riverside",
    "Pleasant Hill": "Contra Costa",
    "Madera": "Madera",
    "Alhambra": "Los Angeles",
    "San Marcos": "San Diego",
    "Livingston": "Merced",
    "Santa Monica": "Los Angeles",
    "Hemet": "Riverside",
    "Red Bluff": "Tehama",
    "Westmorland": "Imperial",
    "Fontana": "San Bernardino",
    "Lake Forest": "Orange",
    "Imperial": "Imperial",
    "Eastvale": "Riverside",
    "Livermore": "Alameda",
    "Mendota": "Fresno",
    "Vallejo": "Solano",
    "Azusa": "Los Angeles",
    "Mammoth Lakes": "Mono",
    "Crescent City": "Del Norte",
    "Petaluma": "Sonoma",
    "Santa Rosa": "Sonoma",
    "Sanger": "Fresno",
    "Hesperia": "San Bernardino",
    "Los Gatos": "Santa Clara",
    "Menifee": "Riverside",
    "Albany": "Alameda",
    "Ontario": "San Bernardino",
    "Westlake Village": "Los Angeles",
    "Fairfax": "Marin",
    "Rosemead": "Los Angeles",
    "Avenal": "Kings",
    "La Mesa": "San Diego",
    "Pleasanton": "Alameda",
    "Glendale": "Los Angeles",
    "San Joaquin": "Fresno",
    "Anaheim": "Orange",
    "Laguna Hills": "Orange",
    "Dixon": "Solano",
    "Clovis": "Fresno",
    "Montague": "Siskiyou",
    "Eureka": "Humboldt",
    "Oakdale": "Stanislaus",
    "Pacific Grove": "Monterey"
};

// Array of cities for random selection
const cities = Object.keys(cityCountyMapping);
let currentCity = "";

// Function to pick a random city
function getRandomCity() {
    const randomIndex = Math.floor(Math.random() * cities.length);
    return cities[randomIndex];
}

// Function to set the card content
function setCardContent(city) {
    document.getElementById('card-title').textContent = "City";
    document.getElementById('city-name').textContent = city;
    document.getElementById('county-name').textContent = "";
    document.getElementById('county-name').classList.add('hidden');
}

// Function to reveal the county
function revealCounty() {
    document.getElementById('card-title').textContent = "City & County";
    document.getElementById('county-name').textContent = cityCountyMapping[currentCity];
    document.getElementById('county-name').classList.remove('hidden');
    document.getElementById('reveal-button').textContent = 'Next';
}

// Function to show the next city
function showNextCity() {
    document.getElementById('reveal-button').textContent = 'Reveal';
    currentCity = getRandomCity();
    setCardContent(currentCity);
}

// Initial setup
currentCity = getRandomCity();
setCardContent(currentCity);

document.getElementById('reveal-button').addEventListener('click', function() {
    if (this.textContent === 'Reveal') {
        revealCounty();
    } else {
        showNextCity();
    }
});
